"""Initial registry schema and transactional search indexing.

Revision ID: 0001_registry
Revises: None
"""
from pathlib import Path

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

revision = "0001_registry"
down_revision = None
branch_labels = None
depends_on = None


def identity_columns() -> list[sa.Column]:
    # IDs are generated by the application; no UUID extension required.
    return [sa.Column("id", sa.Uuid(), primary_key=True)]


def timestamp_columns() -> list[sa.Column]:
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    ]


def child_columns() -> list[sa.Column]:
    return identity_columns() + [sa.Column(
        "service_id", sa.Uuid(), sa.ForeignKey("services.id", ondelete="CASCADE"), nullable=False
    )]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "servers", *identity_columns(), *timestamp_columns(),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("hostname", sa.String(253)), sa.Column("ip", pg.INET(), nullable=False),
        sa.Column("ssh_port", sa.Integer(), nullable=False, server_default="22"),
        sa.Column("ssh_user", sa.String(100)), sa.Column("description", sa.Text()),
        sa.Column("location", sa.String(200)),
        sa.Column("tags", pg.ARRAY(sa.String(100)), nullable=False, server_default=sa.text("'{}'")),
        sa.CheckConstraint("ssh_port BETWEEN 1 AND 65535", name=op.f("ck_servers_ssh_port_range")),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_servers_name_not_blank")),
        sa.CheckConstraint("masklen(ip) = CASE family(ip) WHEN 4 THEN 32 ELSE 128 END", name=op.f("ck_servers_ip_host")),
    )
    op.create_index("uq_servers_name_lower", "servers", [sa.text("lower(name)")], unique=True)
    op.create_index("ix_servers_ip", "servers", ["ip"])
    op.create_table(
        "services", *identity_columns(), *timestamp_columns(),
        sa.Column("server_id", sa.Uuid(), sa.ForeignKey("servers.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("name", sa.String(200), nullable=False), sa.Column("description", sa.Text()),
        sa.Column("project", sa.String(200)), sa.Column("environment", sa.String(100)),
        sa.Column("service_type", sa.String(100)),
        sa.Column("status", sa.String(20), nullable=False, server_default="unknown"),
        sa.Column("container_name", sa.String(255)), sa.Column("docker_image", sa.String(500)),
        sa.Column("compose_path", sa.String(2000)), sa.Column("working_directory", sa.String(2000)),
        sa.Column("healthcheck_url", sa.String(2048)), sa.Column("swagger_url", sa.String(2048)),
        sa.Column("management_url", sa.String(2048)), sa.Column("owner", sa.String(200)),
        sa.Column("notes", sa.Text()), sa.Column("last_accessed_at", sa.DateTime(timezone=True)),
        sa.Column("access_count", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("search_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("search_vector", pg.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, search_text)", persisted=True), nullable=False),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_services_name_not_blank")),
        sa.CheckConstraint("status IN ('unknown', 'running', 'stopped', 'degraded')", name=op.f("ck_services_status_values")),
        sa.CheckConstraint("access_count >= 0", name=op.f("ck_services_access_count_nonnegative")),
    )
    op.create_index("uq_services_server_name_lower", "services", ["server_id", sa.text("lower(name)")], unique=True)
    for column in ("server_id", "project", "environment", "last_accessed_at", "access_count"):
        op.create_index(f"ix_services_{column}", "services", [column])
    op.create_index("ix_services_search_text_trgm", "services", ["search_text"], postgresql_using="gin", postgresql_ops={"search_text": "gin_trgm_ops"})
    op.create_index("ix_services_search_vector", "services", ["search_vector"], postgresql_using="gin")
    op.create_table(
        "service_ports", *child_columns(),
        sa.Column("name", sa.String(100), nullable=False), sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(20), nullable=False, server_default="tcp"),
        sa.Column("description", sa.Text()),
        sa.CheckConstraint("port BETWEEN 1 AND 65535", name=op.f("ck_service_ports_port_range")),
        sa.CheckConstraint("protocol IN ('tcp','udp','http','https','grpc','amqp','amqps','redis','postgresql','other')", name=op.f("ck_service_ports_protocol_values")),
        sa.UniqueConstraint("service_id", "port", "protocol", "name"),
    )
    op.create_index("ix_service_ports_port", "service_ports", ["port"])
    op.create_table("service_aliases", *child_columns(), sa.Column("alias", sa.String(200), nullable=False))
    op.create_index("uq_service_aliases_value_lower", "service_aliases", ["service_id", sa.text("lower(alias)")], unique=True)
    op.create_table(
        "service_tags",
        sa.Column("service_id", sa.Uuid(), sa.ForeignKey("services.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("tag", sa.String(100), primary_key=True),
    )
    op.create_index("uq_service_tags_value_lower", "service_tags", ["service_id", sa.text("lower(tag)")], unique=True)
    op.create_index("ix_service_tags_tag", "service_tags", ["tag"])
    op.create_table(
        "service_commands", *child_columns(), sa.Column("name", sa.String(100), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("command_type", sa.String(20), nullable=False, server_default="custom"),
        sa.CheckConstraint("command_type IN ('ssh','start','stop','restart','logs','custom')", name=op.f("ck_service_commands_type_values")),
    )
    op.create_table(
        "service_endpoints", *child_columns(), sa.Column("name", sa.String(100), nullable=False),
        sa.Column("url", sa.String(2048), nullable=False),
        sa.Column("endpoint_type", sa.String(20), nullable=False, server_default="endpoint"),
        sa.CheckConstraint("endpoint_type IN ('endpoint','swagger','management','healthcheck','metrics','other')", name=op.f("ck_service_endpoints_type_values")),
    )
    for table in ("service_ports", "service_aliases", "service_commands", "service_endpoints"):
        op.create_index(f"ix_{table}_service_id", table, ["service_id"])

    # This SQL belongs to this immutable migration, never to current ORM metadata.
    sql = Path(__file__).with_name("0001_search.sql").read_text(encoding="utf-8")
    # Each block is a full SQL statement; do not split on function-body semicolons.
    for statement in sql.split("-- statement-break"):
        if statement.strip():
            op.execute(sa.schema.DDL(statement))


def downgrade() -> None:
    for table in ("service_endpoints", "service_commands", "service_tags", "service_aliases", "service_ports", "services", "servers"):
        op.drop_table(table)
    for signature in (
        "portatlas_child_changed()", "portatlas_service_changed()", "portatlas_server_changed()",
        "portatlas_touch_updated_at()", "portatlas_refresh_search(uuid)",
    ):
        op.execute(f"DROP FUNCTION IF EXISTS {signature}")
    # Leave pg_trgm installed: another application may depend on it.
